const SUPABASE_URL='https://uipapbtndjctyzvlreoa.supabase.co';
const SUPABASE_KEY='sb_publishable_Inoee5YHcjCLCamrmE-vfA_LLWPK7CT';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s), money=n=>`MVR ${Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:3})}`;
const unitMoney=n=>`MVR ${Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:6})}`;
const localDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Indian/Maldives',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const state={products:[],vendors:[],bills:[],billItems:[],rates:[],inventory:[],purchaseOrders:[],movements:[],settings:[],page:'dashboard',selectedVendor:null,items:[],poItems:[],editingBillId:null};
const pages=[['dashboard','▦','Dashboard'],['new-bill','＋','Add Bill'],['bill-history','▤','Bills'],['products','□','Products'],['vendors','♙','Vendors'],['insights','◒','Insights'],['settings','⚙','Settings']];
const pageLabels={'item-analysis':'Item Analysis','rate-dashboard':'Rate Dashboard','purchase-orders':'Purchase Orders',inventory:'Inventory',reports:'Reports',analytics:'Analytics',backup:'Data Backup','price-cards':'Price Cards','rate-history':'Rate History'};
const purchaseUnits=['KG','G','PC','DOZ','PKT','L','ML','M','BOX','PACKAGE','CASE','HALF CASE','CARTON','BAG','BUNDLE','BOTTLE','CAN','JAR','TIN','TUB','ROLL','TUBE'];
const normalizeUnit=value=>({PIECE:'PC',PCS:'PC',DOZEN:'DOZ',PACK:'PKT',PACKET:'PKT',LITRE:'L',LITER:'L'}[String(value||'').toUpperCase()]||String(value||'PC').toUpperCase());
const unitOptions=value=>purchaseUnits.map(u=>`<option ${u===normalizeUnit(value)?'selected':''}>${u}</option>`).join('');
const categoryAliases={beverages:'Beverage',sauces:'Sauce',buiscuit:'Biscuit',dry:'Dry Items','dry items':'Dry Items','food coloring':'Colour',ketchup:'Sauce','soft drinks':'Beverage','energy drinks':'Beverage',takeaway:'Takeaway',suger:'Sugar',syrup:'Syrup',veg:'Vegetables',tuna:'Tuna',tin:'Canned'};
function canonicalCategory(value){const raw=String(value||'Uncategorised').trim().toLowerCase();return categoryAliases[raw]||raw.replace(/\b\w/g,c=>c.toUpperCase())}
function inferPack(product){const text=`${product.name||''} ${product.unit||''}`.replace(/,/g,'');const matches=[...text.matchAll(/(\d+(?:\.\d+)?)\s*[x×*]\s*(\d+(?:\.\d+)?)\s*(kg|g|gm|grams?|ml|l|ltr|litres?|pcs?|pc)\b/gi)];const m=matches.at(-1);if(m){const raw=m[3].toUpperCase(),unit=/^(PC|PCS)$/.test(raw)?'PCS':/^(GM|GRAM|GRAMS)$/.test(raw)?'G':/^(LTR|LITRE|LITRES)$/.test(raw)?'L':raw;return {pack_quantity:Number(m[1]),pack_size:Number(m[2]),pack_size_unit:unit}}return {pack_quantity:product.pack_quantity||1,pack_size:product.pack_size||1,pack_size_unit:product.pack_size_unit||(/KG|GRAM/i.test(product.unit||'')?'KG':/ML|LTR|LITRE/i.test(product.unit||'')?'L':/PC|PCK|PACK|BOX|CTN|CASE/i.test(product.unit||'')?'PCS':'UNIT')}}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function nav(){ $('#nav').innerHTML=pages.map(([id,ico,label])=>`<button class="nav-link ${state.page===id?'active':''}" data-page="${id}"><span class="ico">${ico}</span><span>${label}</span></button>`).join(''); document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page)); }
async function fetchAll(table,order,columnAscending=true){const pageSize=1000,rows=[];for(let from=0;;from+=pageSize){let query=db.from(table).select('*').range(from,from+pageSize-1);if(order)query=query.order(order,{ascending:columnAscending});const {data,error}=await query;if(error)throw error;rows.push(...(data||[]));if(!data||data.length<pageSize)break}return rows}
async function load(){
  const {data:member,error:memberError}=await db.from('supply_members').select('role,active').maybeSingle();
  if(memberError)throw memberError;if(!member?.active)throw new Error('This account is not an active SupplyFlow member.');
  const [p,v,b,bi,r,i,po,m,s]=await Promise.all([
    fetchAll('supply_products','name'),fetchAll('supply_vendors','vendor_name'),fetchAll('supply_bills','bill_date',false),fetchAll('supply_bill_items'),fetchAll('supply_rate_history','effective_date',false),fetchAll('supply_inventory'),fetchAll('supply_purchase_orders','order_date',false),fetchAll('supply_inventory_movements','movement_date',false),fetchAll('supply_settings')]);
  Object.assign(state,{products:p,vendors:v,bills:b,billItems:bi,rates:r,inventory:i,purchaseOrders:po,movements:m,settings:s});
  if(!state.products.length&&!state.vendors.length)throw new Error('Your account connected, but no products or vendors are visible. Check membership access.');
}
function closeMenu(){document.querySelector('.sidebar')?.classList.remove('open');$('#sidebarBackdrop')?.classList.remove('open');$('#menuBtn')?.setAttribute('aria-expanded','false')}
function startBill(){state.items=[];state.selectedVendor=null;state.editingBillId=null;go('new-bill')}
function go(id){state.page=id;nav();const label=state.editingBillId&&id==='new-bill'?'Modify Bill':pages.find(x=>x[0]===id)?.[2]||pageLabels[id]||id;$('#pageTitle').textContent=label;$('#pageEyebrow').textContent=id==='dashboard'?'OVERVIEW':'SUPPLY MANAGEMENT';$('#quickBill').classList.toggle('hidden',id==='new-bill');render();closeMenu()}
const kpi=(label,value,hint)=>`<div class="card kpi"><div class="label">${label}</div><div class="value">${value}</div><div class="hint">${hint}</div></div>`;
function dashboard(){const total=state.bills.reduce((a,b)=>a+Number(b.total_amount),0),gst=state.bills.reduce((a,b)=>a+Number(b.gst_amount),0),month=localDate().slice(0,7),monthly=state.bills.filter(b=>b.bill_date?.startsWith(month)).reduce((a,b)=>a+Number(b.total_amount),0),low=state.inventory.filter(i=>Number(i.quantity)<=Number(i.reorder_level));const vendorSpend={};state.bills.forEach(b=>vendorSpend[b.vendor_name]=(vendorSpend[b.vendor_name]||0)+Number(b.total_amount));const top=Object.entries(vendorSpend).sort((a,b)=>b[1]-a[1]).slice(0,5);return `<div class="grid kpi-grid">${kpi('TOTAL PURCHASES',money(total),`${state.bills.length} bills`)}${kpi('THIS MONTH',money(monthly),'Current month')}${kpi('GST TOTAL',money(gst),'Recorded tax')}${kpi('LOW STOCK',low.length,'At or below reorder level')}</div><div class="grid content-grid"><section class="card"><div class="section-head"><h3>Recent bills</h3><button class="btn" onclick="go('bill-history')">View all</button></div>${billTable(state.bills.slice(0,7))}</section><section class="card"><div class="section-head"><h3>Top vendors</h3><button class="btn" onclick="go('analytics')">Analytics</button></div>${top.length?top.map(([name,value],i)=>`<div class="setting-row"><span>${i+1}. ${esc(name)}</span><strong>${money(value)}</strong></div>`).join(''):'<div class="empty"><strong>No spending yet</strong>Saved bills will appear here.</div>'}</section></div><div class="grid kpi-grid dashboard-secondary">${kpi('PRODUCTS',state.products.length,'Active catalogue')}${kpi('VENDORS',state.vendors.length,'Approved suppliers')}${kpi('PURCHASE ORDERS',state.purchaseOrders.length,'All statuses')}${kpi('RATE CHANGES',state.rates.length,'Historical records')}</div>`}
function billTable(rows){return rows.length?`<div class="table-wrap"><table><thead><tr><th>Date</th><th>Bill</th><th>Vendor</th><th>Status</th><th>Total</th><th>Actions</th></tr></thead><tbody>${rows.map(b=>`<tr><td>${esc(b.bill_date)}</td><td>${esc(b.bill_number)}</td><td>${esc(b.vendor_name)}</td><td><span class="badge ${b.payment_status==='paid'?'good':'warn'}">${esc(b.payment_status)}</span></td><td class="money">${money(b.total_amount)}</td><td><div class="row-actions"><button class="btn" onclick="showBill(${b.id})">View</button><button class="btn" onclick="editBill(${b.id})">Modify</button><button class="btn danger" onclick="deleteBill(${b.id})">Delete</button></div></td></tr>`).join('')}</tbody></table></div>`:`<div class="empty"><strong>No bills yet</strong>Create your first bill to start tracking spend.</div>`}
window.showBill=id=>{const b=state.bills.find(x=>x.id===id),items=state.billItems.filter(x=>x.bill_id===id);if(!b)return;$('#pageTitle').textContent=`Bill ${b.bill_number}`;$('#page').innerHTML=`<section class="card bill-detail"><div class="section-head"><div><p class="eyebrow">PURCHASE BILL</p><h3>${esc(b.bill_number)}</h3></div><div><button class="btn" onclick="go('bill-history')">Back</button> <button class="btn primary" onclick="printBill(${b.id})">Print</button></div></div><div class="vendor-summary"><div><small>Vendor</small><strong>${esc(b.vendor_name)}</strong></div><div><small>TIN</small><strong>${esc(b.vendor_tin||'—')}</strong></div><div><small>Mobile</small><strong>${esc(b.vendor_mobile||'—')}</strong></div><div><small>Date</small><strong>${esc(b.bill_date)}</strong></div></div><div class="table-wrap"><table><thead><tr><th>Product</th><th>Category</th><th>Quantity</th><th>Unit</th><th>Packing</th><th>Rate</th><th>Total</th></tr></thead><tbody>${items.map(i=>`<tr><td>${esc(i.product_name)}</td><td>${esc(i.category||'—')}</td><td>${i.quantity}</td><td>${esc(i.purchase_unit||i.unit)}</td><td>${i.pack_quantity} × ${i.pack_size} ${esc(i.pack_size_unit)}</td><td>${money(i.rate)}</td><td>${money(i.line_total)}</td></tr>`).join('')}</tbody></table></div><div class="bill-summary detail-summary"><div><span>Subtotal</span><strong>${money(b.subtotal)}</strong></div><div><span>GST ${Number(b.gst_rate)||0}%</span><strong>${money(b.gst_amount)}</strong></div><div class="grand"><span>Grand total</span><strong>${money(b.total_amount)}</strong></div></div><p class="muted">Payment: ${esc(b.payment_status)} · ${esc(b.payment_method)}${b.notes?` · ${esc(b.notes)}`:''}</p></section>`}
const renderBillDetail=window.showBill;window.showBill=id=>{renderBillDetail(id);const actions=document.querySelector('.bill-detail .section-head>div:last-child');if(actions)actions.insertAdjacentHTML('beforeend',` <button class="btn" onclick="editBill(${id})">Modify</button> <button class="btn danger" onclick="deleteBill(${id})">Delete</button>`)}
window.editBill=id=>{const b=state.bills.find(x=>x.id===id);if(!b)return toast('Bill not found');state.editingBillId=id;state.items=state.billItems.filter(x=>x.bill_id===id).map(x=>({...x,quantity:Number(x.quantity),rate:Number(x.rate),pack_quantity:Number(x.pack_quantity)||1,pack_size:Number(x.pack_size)||1,price_per_base_unit:Number(x.price_per_base_unit)||0,add_gst:Number(x.gst_amount)>0}));state.selectedVendor=state.vendors.find(v=>String(v.id)===String(b.vendor_id))||null;go('new-bill');const form=$('#billForm');form.elements.bill_number.value=b.bill_number;form.elements.bill_date.value=b.bill_date;form.elements.payment_status.value=b.payment_status;form.elements.payment_method.value=b.payment_method;form.elements.notes.value=b.notes||'';$('#vendorSelect').value=String(b.vendor_id||'');$('#vendorSelect').dispatchEvent(new Event('change'));$('#saveBillBtn').textContent='Save Changes';updateBillSummary();window.scrollTo({top:0,behavior:'smooth'})}
window.deleteBill=async id=>{const b=state.bills.find(x=>x.id===id);if(!b||!confirm(`Delete bill ${b.bill_number}? This will also reverse its rate and inventory records.`))return;const {error}=await db.rpc('delete_supply_bill',{p_bill_id:id});if(error)return toast(error.message);await load();toast('Bill deleted');go('bill-history')}
window.printBill=id=>{showBill(id);window.print()}
function newBill(){return `<form id="billForm" class="card form-card professional-bill" novalidate><div class="step-head"><span>1</span><div><h3>Bill details</h3><p>Select the vendor and invoice date.</p></div></div><div class="form-grid three"><label>Invoice number<input name="bill_number" value="BILL-${Date.now().toString().slice(-7)}"></label><label>Invoice date<input name="bill_date" type="date" value="${localDate()}"></label><label>Vendor<select id="vendorSelect"><option value="">Select vendor…</option>${state.vendors.map(v=>`<option value="${v.id}">${esc(v.vendor_name)}</option>`).join('')}<option value="__create">＋ Create vendor</option></select></label></div><div id="vendorSummary" class="vendor-summary hidden"></div><div class="step-head"><span>2</span><div><h3>Add items</h3><p>Choose product, quantity and price. Packing is filled automatically.</p></div></div><div class="form-grid four item-fields"></div><div id="packPreview" class="pack-preview">Choose a product to begin.</div><div class="item-add-row"><button id="addItem" type="button" class="btn primary">＋ Add item</button></div><div id="itemsTable"></div><div class="step-head"><span>3</span><div><h3>Save bill</h3><p>Check the total and save.</p></div></div><div class="form-grid three"><label>Payment<select name="payment_status"><option>paid</option><option>pending</option><option>partial</option></select></label><label>Method<select name="payment_method"><option>cash</option><option>bank</option><option>card</option><option>credit</option></select></label><label>Remarks (optional)<input name="notes"></label></div><p id="billMessage" class="form-error" role="alert"></p><div class="dialog-actions bill-actions"><span class="save-note">A bill summary opens after saving.</span><button id="saveBillBtn" type="button" class="btn primary">Save Bill</button></div></form>`}
function productOptions(rows){return rows.filter(p=>p.name?.trim()).map(p=>`<option value="${p.id}">${esc(p.name)} · ${esc(canonicalCategory(p.category))}</option>`).join('')}
function lineAmounts(x){const gross=x.quantity*x.rate,gst=x.add_gst?gross*.08:0;return {gst,total:gross+gst}}
function renderItems(){const box=$('#itemsTable');if(!box)return;box.innerHTML=state.items.length?`<div class="table-wrap item-rows"><table><thead><tr><th>Description</th><th>Packing format</th><th>Unit</th><th>Rate</th><th>GST</th><th>Total</th><th></th></tr></thead><tbody>${state.items.map((x,i)=>{const amount=lineAmounts(x);return `<tr><td><strong>${esc(x.product_name)}</strong></td><td>${x.pack_quantity}x${x.pack_size}</td><td>${esc(x.pack_size_unit)}</td><td>${money(x.rate)}</td><td>${x.add_gst?'8%':'—'}</td><td class="money">${money(amount.total)}</td><td><button type="button" class="btn danger" aria-label="Remove ${esc(x.product_name)}" onclick="removeItem(${i})">×</button></td></tr>`}).join('')}</tbody></table></div><div class="add-another-row"><span>${state.items.length} item${state.items.length===1?'':'s'} in this bill</span><button type="button" class="btn" onclick="document.querySelector('#productSelect')?.focus()">＋ Add another item</button></div>`:'<div class="empty"><strong>No items yet</strong>Add the first item above.</div>'}
window.removeItem=i=>{state.items.splice(i,1);renderItems();updateBillSummary()};
function listPage(kind){const isP=kind==='products',rows=isP?state.products.filter(p=>p.name?.trim()):state.vendors;return `<div class="toolbar"><input id="listSearch" class="search" placeholder="Search ${kind}…"><button class="btn primary" id="createRecord">＋ Add ${isP?'Product':'Vendor'}</button></div><div id="listResults">${dataTable(kind,rows)}</div>`}
function dataTable(kind,rows){if(kind==='products')return `<div class="table-wrap"><table><thead><tr><th>Product</th><th>Category</th><th>Unit</th><th>Vendor</th><th>Rate</th></tr></thead><tbody>${rows.filter(p=>p.name?.trim()).map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.category||'—')}</td><td>${esc(p.unit||'—')}</td><td>${esc(p.vendor_name||'—')}</td><td class="money">${money(p.rate)}</td></tr>`).join('')}</tbody></table></div>`;return `<div class="table-wrap"><table><thead><tr><th>Vendor</th><th>TIN</th><th>Mobile</th><th>Address</th><th>Budget</th></tr></thead><tbody>${rows.map(v=>`<tr><td>${esc(v.vendor_name)}</td><td>${esc(v.tin_number||'—')}</td><td>${esc(v.contact_number||'—')}</td><td>${esc(v.address||'—')}</td><td class="money">${money(v.total_budget)}</td></tr>`).join('')}</tbody></table></div>`}
function latestRates(rows){const latest=new Map();rows.forEach(r=>{if(!latest.has(r.product_id))latest.set(r.product_id,r)});return [...latest.values()]}
function currentPriceRows(){const rows=latestRates(state.rates),seen=new Set(rows.map(r=>r.product_id));state.products.forEach(p=>{if(!seen.has(p.id)&&p.rate!=null)rows.push({product_id:p.id,product_name:p.name,vendor_name:p.vendor_name,unit:p.purchase_unit||p.unit,rate:p.rate,effective_date:'Current rate'})});return rows}
function rates(cards=false){if(cards){const rows=currentPriceRows();return `<div class="toolbar"><input id="cardSearch" class="search" placeholder="Search product, vendor or unit…"></div><div id="cardResults" class="grid price-cards">${priceCardHtml(rows)}</div>`}return `<div class="toolbar"><input id="rateSearch" class="search" placeholder="Search product, vendor, unit or date…"></div><div id="rateResults">${rateTable(state.rates)}</div>`}
function rateTable(rows){return rows.length?`<div class="table-wrap"><table><thead><tr><th>Date</th><th>Product</th><th>Vendor</th><th>Unit</th><th>Rate</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.effective_date)}</td><td>${esc(r.product_name)}</td><td>${esc(r.vendor_name||'—')}</td><td>${esc(r.unit||'—')}</td><td class="money">${money(r.rate)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty"><strong>No rate history yet</strong>Rates are saved automatically from bills.</div>'}
function priceMetrics(r){const product=state.products.find(p=>p.id===r.product_id)||{},inferred=inferPack(product),packQty=Number(product.pack_quantity)||Number(inferred.pack_quantity)||1,packSize=Number(product.pack_size)||Number(inferred.pack_size)||1,total=packQty*packSize,measure=String(product.pack_size_unit||inferred.pack_size_unit||product.unit||r.unit||'UNIT').toUpperCase(),rate=Number(r.rate)||0;if(measure==='G')return {pack:`${packQty}x${packSize} G`,primaryLabel:'Price / KG',primary:rate/total*1000,smallLabel:'Price / G',small:rate/total};if(measure==='KG')return {pack:`${packQty}x${packSize} KG`,primaryLabel:'Price / KG',primary:rate/total,smallLabel:'Price / G',small:rate/total/1000};if(measure==='ML')return {pack:`${packQty}x${packSize} ML`,primaryLabel:'Price / L',primary:rate/total*1000,smallLabel:'Price / ML',small:rate/total};if(measure==='L')return {pack:`${packQty}x${packSize} L`,primaryLabel:'Price / L',primary:rate/total,smallLabel:'Price / ML',small:rate/total/1000};return {pack:`${packQty}x${packSize} ${measure}`,primaryLabel:'Price / Unit',primary:rate/total,smallLabel:null,small:null}}
function priceCardHtml(rows){return rows.length?rows.map(r=>{const m=priceMetrics(r);return `<article class="card price-card"><div class="price-card-head"><h3>${esc(r.product_name)}</h3><span class="badge">${esc(m.pack)}</span></div><div class="rate">${money(r.rate)} <small>pack rate</small></div><div class="unit-rate-grid"><div><small>${m.primaryLabel}</small><strong>${money(m.primary)}</strong></div>${m.smallLabel?`<div class="gram-rate"><small>${m.smallLabel}</small><strong>${unitMoney(m.small)}</strong></div>`:''}</div><p class="muted">${esc(r.vendor_name||'No vendor')} · ${esc(r.effective_date)}</p></article>`}).join(''):'<div class="empty"><strong>No price cards yet</strong>No product rates are available.</div>'}
function itemAnalysis(){const map=new Map();state.billItems.forEach(i=>{const x=map.get(i.product_id)||{name:i.product_name,unit:i.purchase_unit||i.unit,quantity:0,value:0,purchases:0};x.quantity+=Number(i.quantity)||0;x.value+=Number(i.line_total)||Number(i.quantity)*Number(i.rate)||0;x.purchases++;map.set(i.product_id,x)});const rows=[...map.values()].sort((a,b)=>b.value-a.value);return `<div class="toolbar"><input id="itemAnalysisSearch" class="search" placeholder="Search items…"><span class="badge">${rows.length} items</span></div><section class="card"><div class="section-head"><div><h3>Item analysis</h3><p class="muted">A simple summary of purchased quantity and cost.</p></div></div><div id="itemAnalysisResults">${itemAnalysisTable(rows)}</div></section>`}
function itemAnalysisTable(rows){return rows.length?`<div class="table-wrap"><table><thead><tr><th>Item</th><th>Purchased</th><th>Entries</th><th>Average cost</th><th>Total cost</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.name)}</td><td>${x.quantity.toLocaleString()} ${esc(x.unit||'')}</td><td>${x.purchases}</td><td>${money(x.quantity?x.value/x.quantity:0)}</td><td class="money">${money(x.value)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty"><strong>No item data yet</strong>Saved bill items will appear here.</div>'}
function rateDashboard(){const rows=currentPriceRows().map(r=>({...r,metrics:priceMetrics(r)})),top=rows.slice().sort((a,b)=>Number(b.rate)-Number(a.rate)).slice(0,10),max=Math.max(1,...top.map(r=>Number(r.rate)));return `<div class="toolbar"><input id="rateDashboardSearch" class="search" placeholder="Search rates…"><button class="btn" onclick="go('price-cards')">All price cards</button></div><div class="grid content-grid"><section class="card"><div class="section-head"><div><h3>Rate overview</h3><p class="muted">Highest current pack rates.</p></div></div><div class="report-bars">${top.map(r=>`<div class="bar-row"><span>${esc(r.product_name)}</span><div class="bar"><i style="width:${Number(r.rate)/max*100}%"></i></div><strong>${money(r.rate)}</strong></div>`).join('')||'<div class="empty">No rates yet.</div>'}</div></section><section class="card"><div class="section-head"><div><h3>Unit costing</h3><p class="muted">Pack, unit and gram or millilitre rates.</p></div></div><div id="rateDashboardResults">${rateDashboardTable(rows)}</div></section></div>`}
function rateDashboardTable(rows){return rows.length?`<div class="table-wrap"><table><thead><tr><th>Product</th><th>Pack</th><th>Pack rate</th><th>Unit rate</th><th>Small unit rate</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.product_name)}</td><td>${esc(r.metrics.pack)}</td><td>${money(r.rate)}</td><td>${esc(r.metrics.primaryLabel)}: ${money(r.metrics.primary)}</td><td>${r.metrics.smallLabel?`${esc(r.metrics.smallLabel)}: ${unitMoney(r.metrics.small)}`:'—'}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No rates yet.</div>'}
function purchaseOrders(){return `<section class="card erp-form"><div class="section-head"><div><h3>Create purchase order</h3><p class="muted">Create an order before receiving the supplier bill.</p></div></div><div class="form-grid four"><label>PO number<input id="poNumber" value="PO-${Date.now().toString().slice(-7)}"></label><label>Order date<input id="poDate" type="date" value="${localDate()}"></label><label>Expected date<input id="poExpected" type="date"></label><label>Vendor<select id="poVendor"><option value="">Select vendor…</option>${state.vendors.map(v=>`<option value="${v.id}">${esc(v.vendor_name)}</option>`).join('')}</select></label><label class="span-2">Product<select id="poProduct"><option value="">Select product…</option>${productOptions(state.products)}</select></label><label>Quantity<input id="poQty" type="number" min=".001" step=".001" value="1"></label><label>Rate (MVR)<input id="poRate" type="number" min="0" step=".001"></label></div><div class="dialog-actions"><button id="savePo" class="btn primary">Create Purchase Order</button></div></section><section class="card"><div class="section-head"><h3>Purchase orders</h3><span class="badge">${state.purchaseOrders.length} orders</span></div>${poTable(state.purchaseOrders)}</section>`}
function poTable(rows){return rows.length?`<div class="table-wrap"><table><thead><tr><th>Date</th><th>PO number</th><th>Vendor</th><th>Status</th><th>Total</th></tr></thead><tbody>${rows.map(po=>`<tr><td>${esc(po.order_date)}</td><td>${esc(po.po_number)}</td><td>${esc(po.vendor_name)}</td><td><span class="badge ${po.status==='received'?'good':'warn'}">${esc(po.status)}</span></td><td class="money">${money(po.total_amount)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty"><strong>No purchase orders</strong>Create the first order above.</div>'}
async function savePurchaseOrder(){const vendor=state.vendors.find(v=>String(v.id)===$('#poVendor').value),product=state.products.find(p=>String(p.id)===$('#poProduct').value),qty=Number($('#poQty').value),rate=Number($('#poRate').value),poNumber=$('#poNumber').value.trim();if(!poNumber||!vendor||!product||qty<=0||rate<0)return toast('Complete PO number, vendor, product, quantity and rate');const pack=inferPack(product),order={po_number:poNumber,order_date:$('#poDate').value,expected_date:$('#poExpected').value||'',vendor_id:vendor.id,vendor_name:vendor.vendor_name,subtotal:qty*rate,total_amount:qty*rate,status:'draft'},items=[{product_id:product.id,product_name:product.name,category:canonicalCategory(product.category),quantity:qty,purchase_unit:product.purchase_unit,pack_quantity:pack.pack_quantity,pack_size:pack.pack_size,pack_size_unit:pack.pack_size_unit,rate}];const {error}=await db.rpc('create_supply_purchase_order',{p_order:order,p_items:items});if(error)return toast(error.message);await load();toast('Purchase order created atomically');render()}
function inventory(){const map=new Map(state.inventory.map(i=>[i.product_id,i]));return `<section class="card erp-form"><div class="section-head"><div><h3>Record stock movement</h3><p class="muted">Purchases are added automatically from bills. Use this for opening stock, usage and adjustments.</p></div></div><div class="form-grid four"><label class="span-2">Product<select id="movementProduct"><option value="">Select product…</option>${productOptions(state.products)}</select></label><label>Movement<select id="movementType"><option value="opening">Opening stock</option><option value="usage">Stock out / usage</option><option value="adjustment_in">Adjustment in</option><option value="adjustment_out">Adjustment out</option></select></label><label>Quantity<input id="movementQty" type="number" min=".001" step=".001" value="1"></label><label>Reorder level<input id="movementReorder" type="number" min="0" step=".001" value="0"></label><label class="span-2">Notes<input id="movementNotes"></label></div><div class="dialog-actions"><button id="saveMovement" class="btn primary">Save Movement</button></div></section><div class="toolbar"><input id="inventorySearch" class="search" placeholder="Search inventory…"><span class="badge">${state.movements.length} movements</span></div><div id="inventoryResults"><div class="table-wrap"><table><thead><tr><th>Product</th><th>Unit</th><th>On hand</th><th>Reorder level</th><th>Status</th></tr></thead><tbody>${state.products.filter(p=>p.name).map(p=>{const x=map.get(p.id)||{};const low=Number(x.quantity||0)<=Number(x.reorder_level||0);return `<tr><td>${esc(p.name)}</td><td>${esc(p.purchase_unit||'—')}</td><td>${Number(x.quantity||0)}</td><td>${Number(x.reorder_level||0)}</td><td><span class="badge ${low?'warn':'good'}">${low?'Low':'In stock'}</span></td></tr>`}).join('')}</tbody></table></div></div>`}
async function saveMovement(){const product=state.products.find(p=>String(p.id)===$('#movementProduct').value),type=$('#movementType').value,qty=Number($('#movementQty').value),reorder=Number($('#movementReorder').value)||0;if(!product||qty<=0)return toast('Select a product and valid quantity');const {error}=await db.rpc('record_supply_inventory_movement',{p_product_id:product.id,p_movement_type:type,p_quantity:qty,p_purchase_unit:product.purchase_unit,p_reorder_level:reorder,p_notes:$('#movementNotes').value});if(error)return toast(error.message);await load();toast('Inventory movement saved atomically');render()}
function reports(){const categories=[...new Set(state.billItems.map(i=>i.category).filter(Boolean))].sort();return `<section class="card report-filter"><div class="section-head"><div><h3>Purchase reports</h3><p class="muted">Filter bills by date, vendor, category, payment or GST.</p></div></div><div class="form-grid four"><label>From date<input id="reportFrom" type="date"></label><label>To date<input id="reportTo" type="date"></label><label>Vendor<select id="reportVendor"><option value="">All vendors</option>${state.vendors.map(v=>`<option>${esc(v.vendor_name)}</option>`).join('')}</select></label><label>Category<select id="reportCategory"><option value="">All categories</option>${categories.map(c=>`<option>${esc(c)}</option>`).join('')}</select></label><label>Payment<select id="reportPayment"><option value="">All statuses</option><option>paid</option><option>pending</option><option>partial</option></select></label><label>GST<select id="reportGst"><option value="">All GST types</option><option value="none">No GST</option><option value="included">Included</option><option value="added">Added</option></select></label></div></section><div id="reportResults">${reportResults(state.bills)}</div>`}
function reportResults(bills){const agg={};bills.forEach(b=>agg[b.vendor_name]=(agg[b.vendor_name]||0)+Number(b.total_amount));const rows=Object.entries(agg).sort((a,b)=>b[1]-a[1]),max=rows[0]?.[1]||1,total=bills.reduce((a,b)=>a+Number(b.total_amount),0),gst=bills.reduce((a,b)=>a+Number(b.gst_amount),0);return `<div class="grid kpi-grid">${kpi('BILLS',bills.length,'Filtered records')}${kpi('PURCHASES',money(total),'Grand total')}${kpi('GST',money(gst),'Tax amount')}${kpi('VENDORS',rows.length,'Used in result')}</div><div class="grid content-grid"><section class="card"><div class="section-head"><h3>Vendor spending</h3></div><div class="report-bars">${rows.length?rows.slice(0,12).map(([n,v])=>`<div class="bar-row"><span>${esc(n)}</span><div class="bar"><i style="width:${v/max*100}%"></i></div><strong>${money(v)}</strong></div>`).join(''):'<div class="empty">No matching report data.</div>'}</div></section><section class="card"><h3>Filtered bills</h3>${billTable(bills.slice(0,20))}</section></div>`}
function filterReports(){const from=$('#reportFrom').value,to=$('#reportTo').value,vendor=$('#reportVendor').value,category=$('#reportCategory').value,payment=$('#reportPayment').value,gst=$('#reportGst').value;let allowed=null;if(category){allowed=new Set(state.billItems.filter(i=>i.category===category).map(i=>i.bill_id))}const rows=state.bills.filter(b=>(!from||b.bill_date>=from)&&(!to||b.bill_date<=to)&&(!vendor||b.vendor_name===vendor)&&(!payment||b.payment_status===payment)&&(!gst||b.gst_type===gst)&&(!allowed||allowed.has(b.id)));$('#reportResults').innerHTML=reportResults(rows)}
function analytics(){const vendor={};state.bills.forEach(b=>{const x=vendor[b.vendor_name]||(vendor[b.vendor_name]={bills:0,total:0,last:''});x.bills++;x.total+=Number(b.total_amount);if(b.bill_date>x.last)x.last=b.bill_date});const categories={};state.billItems.forEach(i=>categories[i.category||'Uncategorised']=(categories[i.category||'Uncategorised']||0)+Number(i.line_total));const rateChanges=[];const grouped={};state.rates.slice().sort((a,b)=>a.effective_date.localeCompare(b.effective_date)).forEach(r=>{const prev=grouped[r.product_id];if(prev&&Number(prev.rate)>0){const diff=Number(r.rate)-Number(prev.rate);rateChanges.push({...r,previous:Number(prev.rate),difference:diff,percent:diff/Number(prev.rate)*100})}grouped[r.product_id]=r});return `<div class="grid kpi-grid">${kpi('VENDOR SPEND',money(state.bills.reduce((a,b)=>a+Number(b.total_amount),0)),'All vendors')}${kpi('TOP CATEGORY',Object.entries(categories).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—','By purchased value')}${kpi('PRICE CHANGES',rateChanges.length,'Comparable rates')}${kpi('AVERAGE BILL',money(state.bills.length?state.bills.reduce((a,b)=>a+Number(b.total_amount),0)/state.bills.length:0),'Per bill')}</div><div class="grid content-grid"><section class="card"><div class="section-head"><h3>Vendor performance</h3></div><div class="table-wrap"><table><thead><tr><th>Vendor</th><th>Bills</th><th>Total spending</th><th>Average bill</th><th>Last purchase</th></tr></thead><tbody>${Object.entries(vendor).sort((a,b)=>b[1].total-a[1].total).map(([name,x])=>`<tr><td>${esc(name)}</td><td>${x.bills}</td><td>${money(x.total)}</td><td>${money(x.total/x.bills)}</td><td>${esc(x.last)}</td></tr>`).join('')}</tbody></table></div></section><section class="card"><div class="section-head"><h3>Recent price changes</h3></div>${rateChanges.length?`<div class="table-wrap"><table><thead><tr><th>Product</th><th>Previous</th><th>New</th><th>Change</th></tr></thead><tbody>${rateChanges.slice(-15).reverse().map(r=>`<tr><td>${esc(r.product_name)}</td><td>${money(r.previous)}</td><td>${money(r.rate)}</td><td><span class="badge ${r.difference<=0?'good':'warn'}">${r.percent>=0?'+':''}${r.percent.toFixed(1)}%</span></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty"><strong>No comparable rates yet</strong>At least two purchases of a product are needed.</div>'}</section></div>`}
function insights(){return `<div class="grid insight-menu"><button class="card insight-link" onclick="go('item-analysis')"><span>◫</span><div><strong>Item Analysis</strong><small>Quantity and item costs</small></div><b>›</b></button><button class="card insight-link" onclick="go('rate-dashboard')"><span>↗</span><div><strong>Rate Dashboard</strong><small>Pack, unit and gram rates</small></div><b>›</b></button><button class="card insight-link" onclick="go('reports')"><span>▤</span><div><strong>Reports</strong><small>Filter purchases and GST</small></div><b>›</b></button><button class="card insight-link" onclick="go('analytics')"><span>◒</span><div><strong>Business Analytics</strong><small>Vendors and price changes</small></div><b>›</b></button></div>`}
function settings(){return `<section class="card"><h3>Settings</h3><div class="setting-row"><div><strong>Currency</strong><p class="muted">Used throughout the application</p></div><span>MVR</span></div><div class="setting-row"><div><strong>Database</strong><p class="muted">Supabase live connection</p></div><span class="badge good">Connected</span></div></section><section class="card settings-tools"><h3>More tools</h3><div class="tool-buttons"><button class="btn" onclick="go('purchase-orders')">Purchase Orders</button><button class="btn" onclick="go('inventory')">Inventory</button><button class="btn" onclick="go('backup')">Data Backup</button></div></section>`}
function backup(){return `<section class="card"><h3>Complete Data Backup</h3><p class="muted" style="margin:8px 0 20px">Download all currently accessible ERP records as one JSON file. Database restoration is an administrator operation and is intentionally not performed from the browser.</p><div class="toolbar" style="justify-content:flex-start"><button id="downloadBackup" class="btn primary">Download complete backup</button></div></section>`}
function render(){const f={dashboard,'new-bill':newBill,'bill-history':()=>`<div class="toolbar"><input id="billSearch" class="search" placeholder="Search bills…"></div><div id="billResults">${billTable(state.bills)}</div>`,insights,'item-analysis':itemAnalysis,'rate-dashboard':rateDashboard,products:()=>listPage('products'),vendors:()=>listPage('vendors'),'purchase-orders':purchaseOrders,'rate-history':()=>rates(false),'price-cards':()=>rates(true),inventory,reports,analytics,settings,backup};const view=f[state.page]||dashboard;$('#page').innerHTML=view();bindPage()}
function bindPage(){
 if(state.page==='new-bill')bindBill();
 if(state.page==='bill-history'){const button=document.createElement('button');button.type='button';button.className='btn primary';button.textContent='＋ Add Bill';button.onclick=startBill;$('#billSearch')?.closest('.toolbar')?.append(button)}
 const searchMap={billSearch:['billResults',q=>billTable(state.bills.filter(b=>`${b.bill_number} ${b.vendor_name} ${b.bill_date} ${b.payment_status} ${b.payment_method} ${b.total_amount}`.toLowerCase().includes(q)))],rateSearch:['rateResults',q=>rateTable(state.rates.filter(r=>`${r.product_name} ${r.vendor_name} ${r.unit} ${r.effective_date} ${r.rate}`.toLowerCase().includes(q)))],cardSearch:['cardResults',q=>priceCardHtml(currentPriceRows().filter(r=>`${r.product_name} ${r.vendor_name} ${r.unit} ${r.effective_date}`.toLowerCase().includes(q)))]};
 Object.entries(searchMap).forEach(([id,[out,fn]])=>{const e=$('#'+id);if(e)e.oninput=()=>$('#'+out).innerHTML=fn(e.value.toLowerCase())});
 if($('#listSearch'))$('#listSearch').oninput=e=>{const q=e.target.value.toLowerCase(),kind=state.page;$('#listResults').innerHTML=dataTable(kind,(kind==='products'?state.products.filter(p=>p.name?.trim()):state.vendors).filter(x=>JSON.stringify(x).toLowerCase().includes(q)))};
 if($('#inventorySearch'))$('#inventorySearch').oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('#inventoryResults tbody tr').forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(q))};
 if($('#itemAnalysisSearch'))$('#itemAnalysisSearch').oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('#itemAnalysisResults tbody tr').forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(q))};
 if($('#rateDashboardSearch'))$('#rateDashboardSearch').oninput=e=>{const q=e.target.value.toLowerCase(),rows=currentPriceRows().map(r=>({...r,metrics:priceMetrics(r)})).filter(r=>`${r.product_name} ${r.vendor_name} ${r.unit} ${r.metrics.pack}`.toLowerCase().includes(q));$('#rateDashboardResults').innerHTML=rateDashboardTable(rows)};
 if(state.page==='purchase-orders'){const section=document.querySelectorAll('.card')[1],input=document.createElement('input');input.className='search';input.placeholder='Search PO, vendor, date, status or total…';section.querySelector('.section-head').append(input);input.oninput=()=>{const q=input.value.toLowerCase();section.querySelectorAll('tbody tr').forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(q))}}
 if($('#createRecord'))$('#createRecord').onclick=()=>state.page==='vendors'?openVendor():toast('Products are imported from the master catalogue');
 if($('#downloadBackup'))$('#downloadBackup').onclick=downloadBackup;
 if($('#savePo'))$('#savePo').onclick=savePurchaseOrder;
 if($('#saveMovement'))$('#saveMovement').onclick=saveMovement;
 ['reportFrom','reportTo','reportVendor','reportCategory','reportPayment','reportGst'].forEach(id=>{if($('#'+id))$('#'+id).onchange=filterReports});
}
function openVendor(prefill=''){const d=$('#vendorDialog');d.querySelector('[name=vendor_name]').value=prefill;d.showModal()}
function setupLineEditor(){const editor=document.querySelector('.item-fields');editor.innerHTML=`<label class="description-field">Description<select id="productSelect"><option value="">Choose product…</option>${productOptions(state.products)}</select></label><label>Packing format<input id="packFormat" value="1x1" placeholder="500x10" inputmode="decimal"></label><label>Unit<select id="packUnit"><option>PC</option><option>KG</option><option>G</option><option>L</option><option>ML</option><option>M</option><option>DOZ</option><option>PKT</option><option>BOX</option><option>PACKAGE</option></select></label><label>Rate (MVR)<input id="itemRate" type="number" min="0" step=".001" placeholder="0.00"></label><label class="gst-check"><span>Add GST</span><input id="itemGst" type="checkbox"><small>8% automatic</small></label><div class="line-total-preview"><small>Total</small><strong id="lineTotal">MVR 0.00</strong></div><input id="itemQty" type="hidden" value="1"><input id="itemUnit" type="hidden" value="PC"><input id="categorySelect" type="hidden" value="">`;$('#addItem').textContent='＋ Add item'}
function bindBill(){
 setupLineEditor();renderItems();mountGstFields();$('#vendorSelect').onchange=e=>{if(e.target.value==='__create'){openVendor();e.target.value='';return}state.selectedVendor=state.vendors.find(v=>String(v.id)===e.target.value)||null;const s=$('#vendorSummary');if(!state.selectedVendor){s.classList.add('hidden');return}s.classList.remove('hidden');s.innerHTML=`<div><small>Vendor</small><strong>${esc(state.selectedVendor.vendor_name)}</strong></div><div><small>TIN</small><strong>${esc(state.selectedVendor.tin_number||'Not available')}</strong></div><div><small>Mobile</small><strong>${esc(state.selectedVendor.contact_number||'Not available')}</strong></div>`};
 $('#categorySelect').onchange=e=>{const category=e.target.value;const rows=category?state.products.filter(p=>canonicalCategory(p.category)===category):state.products;$('#productSelect').innerHTML=`<option value="">Choose product…</option>${productOptions(rows)}`;clearPackFields()};
 $('#productSelect').onchange=e=>{const p=state.products.find(x=>String(x.id)===e.target.value);if(p){const pack=inferPack(p);$('#itemRate').value=p.rate??'';$('#itemUnit').value=normalizeUnit(p.purchase_unit||p.unit);$('#packFormat').value=`${pack.pack_quantity}x${pack.pack_size}`;$('#packUnit').value=pack.pack_size_unit==='PCS'?'PC':pack.pack_size_unit;$('#categorySelect').value=canonicalCategory(p.category);updatePackPreview()}};
 ['itemQty','itemRate','packFormat','packUnit','itemUnit','itemGst'].forEach(id=>$('#'+id).addEventListener('input',updatePackPreview));
 $('#addItem').onclick=addCurrentItem;
 $('#saveBillBtn').onclick=saveBill;
 $('#billForm').onsubmit=e=>{e.preventDefault();saveBill()};
}
function mountGstFields(){const anchor=$('#billMessage');if(!anchor||$('#billSummary'))return;anchor.insertAdjacentHTML('beforebegin',`<div id="billSummary" class="bill-summary"></div>`);updateBillSummary()}
function billTotals(){const subtotal=state.items.reduce((a,x)=>a+x.quantity*x.rate,0),gst=state.items.reduce((a,x)=>a+lineAmounts(x).gst,0);return {gross:subtotal,subtotal,gst,total:subtotal+gst,type:gst?'added':'none',rate:gst?8:0}}
function updateBillSummary(){const box=$('#billSummary');if(!box)return;const t=billTotals();box.innerHTML=`<div><span>Subtotal</span><strong>${money(t.subtotal)}</strong></div><div><span>GST ${t.rate?`(${t.rate}%)`:''}</span><strong>${money(t.gst)}</strong></div><div class="grand"><span>Grand total</span><strong>${money(t.total)}</strong></div>`;renderItems()}
function readPackage(){const value=$('#packFormat').value.trim(),match=value.match(/^(\d+(?:\.\d+)?)\s*[x×*]\s*(\d+(?:\.\d+)?)$/i);return match?{pack_quantity:Number(match[1]),pack_size:Number(match[2])}:null}
function clearPackFields(){$('#productSelect').value='';$('#itemQty').value=1;$('#itemRate').value='';$('#itemUnit').value='PC';$('#packFormat').value='1x1';$('#packUnit').value='PC';$('#itemGst').checked=false;updatePackPreview();$('#productSelect').focus()}
function updatePackPreview(){const p=state.products.find(x=>String(x.id)===$('#productSelect').value),rate=Number($('#itemRate').value),pack=readPackage(),unit=$('#packUnit').value,qty=Number($('#itemQty').value)||0,gst=$('#itemGst')?.checked,total=qty*rate*(gst?1.08:1);if($('#lineTotal'))$('#lineTotal').textContent=money(total);if(!p){$('#packPreview').textContent='Choose a description to begin.';return}if(!pack){$('#packPreview').innerHTML='<strong>Use packing format like 12x1 or 500x10.</strong>';return}const baseCount=pack.pack_quantity*pack.pack_size,baseRate=baseCount>0?rate/baseCount:0;$('#packPreview').innerHTML=`${pack.pack_quantity}x${pack.pack_size} ${esc(unit)} · ${unitMoney(baseRate)} per ${esc(unit)}${gst?' · GST added':''}`}
function billError(message){const box=$('#billMessage');if(box)box.textContent=message;toast(message)}
function addCurrentItem(){const p=state.products.find(x=>String(x.id)===$('#productSelect').value),quantity=Number($('#itemQty').value),raw=$('#itemRate').value,rate=Number(raw),pack=readPackage(),pack_size_unit=$('#packUnit').value,purchase_unit=$('#itemUnit').value.trim(),add_gst=$('#itemGst').checked;if(!p)return billError('Please select a description / product');if(!Number.isFinite(quantity)||quantity<=0)return billError('Quantity must be more than zero');if(raw===''||!Number.isFinite(rate)||rate<0)return billError('Enter a valid rate');if(!purchase_unit)return billError('Select the unit');if(!pack||pack.pack_quantity<=0||pack.pack_size<=0)return billError('Package must use 0x0 format, for example 12x1');const {pack_quantity,pack_size}=pack,price_per_base_unit=rate/(pack_quantity*pack_size);state.items.push({product_id:p.id,product_name:p.name,category:canonicalCategory(p.category),quantity,rate,unit:purchase_unit,purchase_unit,pack_quantity,pack_size,pack_size_unit,price_per_base_unit,add_gst});$('#billMessage').textContent='';clearPackFields();renderItems();updateBillSummary();return true}
async function saveBill(){const form=$('#billForm'),button=$('#saveBillBtn');if(!form)return;if(!state.selectedVendor)return billError('Please select a vendor');if($('#productSelect').value&&!addCurrentItem())return;if(!state.items.length)return billError('Add at least one product before saving');const fd=new FormData(form),billNumber=String(fd.get('bill_number')||'').trim(),billDate=fd.get('bill_date');if(!billNumber)return billError('Enter a bill number');if(!billDate)return billError('Select a bill date');button.disabled=true;button.textContent='Saving…';$('#billMessage').textContent='';const totals=billTotals(),vendorId=state.selectedVendor.id,bill={bill_number:billNumber,bill_date:billDate,vendor_id:vendorId,vendor_name:state.selectedVendor.vendor_name,vendor_tin:state.selectedVendor.tin_number||'',vendor_mobile:state.selectedVendor.contact_number||'',subtotal:totals.subtotal,gst_type:totals.type,gst_rate:totals.rate,gst_amount:totals.gst,total_amount:totals.total,payment_status:fd.get('payment_status'),payment_method:fd.get('payment_method'),notes:fd.get('notes')},items=state.items.map(x=>({...x,gst_amount:lineAmounts(x).gst}));try{const editing=state.editingBillId;const {error}=editing?await db.rpc('update_supply_bill',{p_bill_id:editing,p_bill:bill,p_items:items}):await db.rpc('create_supply_bill',{p_bill:bill,p_items:items});if(error)throw error;state.items=[];state.editingBillId=null;await load();const saved=editing?state.bills.find(b=>b.id===editing):state.bills.find(b=>b.bill_number===billNumber&&String(b.vendor_id)===String(vendorId)&&b.bill_date===billDate);toast(editing?'Bill updated':'Bill saved');if(saved)showBill(saved.id);else go('bill-history')}catch(error){billError(error.message||'Could not save bill');button.disabled=false;button.textContent=state.editingBillId?'Save Changes':'Save Bill'}}
async function saveVendor(e){e.preventDefault();const fd=new FormData(e.target),payload=Object.fromEntries(fd.entries());payload.source_id=Math.max(0,...state.vendors.map(v=>v.source_id||0))+1;payload.total_budget=0;const {data,error}=await db.from('supply_vendors').insert(payload).select().single();if(error)return toast(error.message);state.vendors.push(data);state.vendors.sort((a,b)=>a.vendor_name.localeCompare(b.vendor_name));state.selectedVendor=data;$('#vendorDialog').close();toast('Vendor created');if(state.page==='new-bill'){render();setTimeout(()=>{$('#vendorSelect').value=String(data.id);$('#vendorSelect').dispatchEvent(new Event('change'))})}else render()}
function downloadBackup(){const payload={version:2,exported_at:new Date().toISOString(),record_counts:{products:state.products.length,vendors:state.vendors.length,bills:state.bills.length,bill_items:state.billItems.length,rate_history:state.rates.length,inventory:state.inventory.length,purchase_orders:state.purchaseOrders.length,inventory_movements:state.movements.length,settings:state.settings.length},products:state.products,vendors:state.vendors,bills:state.bills,bill_items:state.billItems,rate_history:state.rates,inventory:state.inventory,purchase_orders:state.purchaseOrders,inventory_movements:state.movements,settings:state.settings};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=`supply-backup-${localDate()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Complete backup downloaded')}
let sessionVersion=0;
function showSignedOut(){sessionVersion++;closeMenu();$('#appShell').classList.add('hidden');$('#loginView').classList.remove('hidden');$('#loginPassword').value='';$('#loginPassword').type='password';$('#togglePassword').textContent='Show';$('#togglePassword').setAttribute('aria-pressed','false');$('#syncState').textContent='● Offline'}
async function applySession(session){const version=++sessionVersion;if(!session){showSignedOut();return}$('#loginView').classList.add('hidden');$('#appShell').classList.remove('hidden');$('#syncState').textContent='● Loading data…';$('#page').innerHTML='<div class="card loading-state"><strong>Loading SupplyFlow database…</strong><p class="muted">Connecting products, vendors and bills.</p></div>';try{await load();if(version!==sessionVersion)return;$('#syncState').textContent=`● Live · ${state.products.length} products`;render()}catch(error){if(version!==sessionVersion)return;$('#syncState').textContent='● Data error';$('#page').innerHTML=`<div class="card load-error"><strong>Database could not load</strong><p>${esc(error.message||'Unknown database error')}</p><div class="dialog-actions"><button class="btn" id="retryLoad">Retry</button><button class="btn danger" id="errorLogout">Logout</button></div></div>`;$('#retryLoad').onclick=()=>applySession(session);$('#errorLogout').onclick=logout}}
async function logout(){const button=$('#logoutBtn');button.disabled=true;button.innerHTML='<span class="ico">…</span><span>Logging out</span>';sessionVersion++;try{const {error}=await db.auth.signOut({scope:'local'});if(error)throw error;showSignedOut();toast('Logged out')}catch(error){toast(error.message||'Logout failed—please try again')}finally{button.disabled=false;button.innerHTML='↪ <span>Logout</span>'}}
async function init(){nav();$('#togglePassword').onclick=()=>{const input=$('#loginPassword'),show=input.type==='password';input.type=show?'text':'password';$('#togglePassword').textContent=show?'Hide':'Show';$('#togglePassword').setAttribute('aria-label',show?'Hide password':'Show password');$('#togglePassword').setAttribute('aria-pressed',String(show));input.focus()};$('#loginForm').onsubmit=async e=>{e.preventDefault();const username=$('#loginUsername').value.trim().toLowerCase(),password=$('#loginPassword').value,submit=e.submitter;$('#loginError').textContent='';submit.disabled=true;const {data,error}=await db.functions.invoke('username-login',{body:{username,password}});if(!error&&data?.access_token&&data?.refresh_token){const {error:sessionError}=await db.auth.setSession({access_token:data.access_token,refresh_token:data.refresh_token});if(!sessionError){submit.disabled=false;return}}submit.disabled=false;$('#loginError').textContent='Username or password is incorrect'};$('#logoutBtn').onclick=logout;$('#quickBill').onclick=startBill;$('#menuBtn').onclick=()=>{const open=document.querySelector('.sidebar').classList.toggle('open');$('#sidebarBackdrop').classList.toggle('open',open);$('#menuBtn').setAttribute('aria-expanded',String(open))};$('#sidebarBackdrop').onclick=closeMenu;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});document.querySelectorAll('.close-dialog').forEach(x=>x.onclick=()=>$('#vendorDialog').close());$('#vendorForm').onsubmit=saveVendor;db.auth.onAuthStateChange((_,session)=>{setTimeout(()=>applySession(session),0)})}
init();
