const SUPABASE_URL='https://uipapbtndjctyzvlreoa.supabase.co';
const SUPABASE_KEY='sb_publishable_Inoee5YHcjCLCamrmE-vfA_LLWPK7CT';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s), money=n=>`MVR ${Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:3})}`;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const state={products:[],vendors:[],bills:[],rates:[],inventory:[],page:'dashboard',selectedVendor:null,items:[]};
const pages=[['dashboard','▦','Dashboard'],['new-bill','＋','New Bill'],['bill-history','▤','Bill History'],['products','□','Products'],['vendors','♙','Vendors'],['rate-history','↗','Rate History'],['price-cards','◇','Price Cards'],['inventory','▥','Inventory'],['reports','◫','Reports'],['settings','⚙','Settings'],['backup','↻','Backup and Restore']];
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function nav(){ $('#nav').innerHTML=pages.map(([id,ico,label])=>`<button class="nav-link ${state.page===id?'active':''}" data-page="${id}"><span class="ico">${ico}</span><span>${label}</span></button>`).join(''); document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page)); }
async function load(){
  const [p,v,b,r,i]=await Promise.all([
    db.from('supply_products').select('*').order('name'),db.from('supply_vendors').select('*').order('vendor_name'),
    db.from('supply_bills').select('*').order('bill_date',{ascending:false}).limit(500),db.from('supply_rate_history').select('*').order('effective_date',{ascending:false}).limit(1000),
    db.from('supply_inventory').select('*')]);
  const error=[p,v,b,r,i].find(x=>x.error)?.error;if(error)throw error;
  Object.assign(state,{products:p.data||[],vendors:v.data||[],bills:b.data||[],rates:r.data||[],inventory:i.data||[]});
}
function go(id){state.page=id;nav();const label=pages.find(x=>x[0]===id)?.[2]||id;$('#pageTitle').textContent=label;$('#pageEyebrow').textContent=id==='dashboard'?'OVERVIEW':'SUPPLY MANAGEMENT';render();document.querySelector('.sidebar').classList.remove('open')}
const kpi=(label,value,hint)=>`<div class="card kpi"><div class="label">${label}</div><div class="value">${value}</div><div class="hint">${hint}</div></div>`;
function dashboard(){const total=state.bills.reduce((a,b)=>a+Number(b.total_amount),0),month=new Date().toISOString().slice(0,7),monthly=state.bills.filter(b=>b.bill_date?.startsWith(month)).reduce((a,b)=>a+Number(b.total_amount),0);return `<div class="grid kpi-grid">${kpi('TOTAL SPEND',money(total),'All recorded bills')}${kpi('THIS MONTH',money(monthly),'Current month')}${kpi('PRODUCTS',state.products.length,'Active catalogue')}${kpi('VENDORS',state.vendors.length,'Approved suppliers')}</div><div class="grid content-grid"><section class="card"><div class="section-head"><h3>Latest bills</h3><button class="btn" onclick="go('bill-history')">View all</button></div>${billTable(state.bills.slice(0,8))}</section><section class="card"><div class="section-head"><h3>Quick overview</h3></div><div class="setting-row"><span>Price records</span><strong>${state.rates.length}</strong></div><div class="setting-row"><span>Inventory items</span><strong>${state.inventory.length}</strong></div><div class="setting-row"><span>Pending bills</span><strong>${state.bills.filter(b=>b.payment_status==='pending').length}</strong></div></section></div>`}
function billTable(rows){return rows.length?`<div class="table-wrap"><table><thead><tr><th>Date</th><th>Bill</th><th>Vendor</th><th>Status</th><th>Total</th></tr></thead><tbody>${rows.map(b=>`<tr><td>${esc(b.bill_date)}</td><td>${esc(b.bill_number)}</td><td>${esc(b.vendor_name)}</td><td><span class="badge ${b.payment_status==='paid'?'good':'warn'}">${esc(b.payment_status)}</span></td><td class="money">${money(b.total_amount)}</td></tr>`).join('')}</tbody></table></div>`:`<div class="empty"><strong>No bills yet</strong>Create your first bill to start tracking spend.</div>`}
function newBill(){return `<form id="billForm" class="card form-card"><div class="form-grid three"><label>Bill number<input name="bill_number" value="BILL-${Date.now().toString().slice(-7)}" required></label><label>Bill date<input name="bill_date" type="date" value="${new Date().toISOString().slice(0,10)}" required></label><label>Vendor<select id="vendorSelect" required><option value="">Select vendor…</option>${state.vendors.map(v=>`<option value="${v.id}">${esc(v.vendor_name)}</option>`).join('')}<option value="__create">＋ Vendor not listed — create</option></select></label></div><div id="vendorSummary" class="vendor-summary hidden"></div><div class="line-editor"><select id="productSelect"><option value="">Choose product…</option>${state.products.filter(p=>p.name).map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select><input id="itemQty" type="number" min=".001" step=".001" value="1" placeholder="Qty"><input id="itemRate" type="number" min="0" step=".001" placeholder="Rate"><input id="itemUnit" placeholder="Unit"><button id="addItem" type="button" class="btn primary">Add</button></div><div id="itemsTable"></div><div class="form-grid three"><label>Payment status<select name="payment_status"><option>paid</option><option>pending</option><option>partial</option></select></label><label>Payment method<select name="payment_method"><option>cash</option><option>bank</option><option>card</option><option>credit</option></select></label><label>Notes<input name="notes"></label></div><div class="dialog-actions"><button type="submit" class="btn primary">Save Bill</button></div></form>`}
function renderItems(){const box=$('#itemsTable');if(!box)return;const total=state.items.reduce((a,x)=>a+x.quantity*x.rate,0);box.innerHTML=state.items.length?`<div class="table-wrap"><table><thead><tr><th>Product</th><th>Qty</th><th>Unit</th><th>Rate</th><th>Total</th><th></th></tr></thead><tbody>${state.items.map((x,i)=>`<tr><td>${esc(x.product_name)}</td><td>${x.quantity}</td><td>${esc(x.unit)}</td><td>${money(x.rate)}</td><td>${money(x.quantity*x.rate)}</td><td><button type="button" class="btn danger" onclick="removeItem(${i})">×</button></td></tr>`).join('')}</tbody></table></div><div class="bill-total"><div class="grand"><span>Total</span><span>${money(total)}</span></div></div>`:'<div class="empty"><strong>No items added</strong>Select a product, quantity and rate.</div>'}
window.removeItem=i=>{state.items.splice(i,1);renderItems()};
function listPage(kind){const isP=kind==='products',rows=isP?state.products:state.vendors;return `<div class="toolbar"><input id="listSearch" class="search" placeholder="Search ${kind}…"><button class="btn primary" id="createRecord">＋ Add ${isP?'Product':'Vendor'}</button></div><div id="listResults">${dataTable(kind,rows)}</div>`}
function dataTable(kind,rows){if(kind==='products')return `<div class="table-wrap"><table><thead><tr><th>Product</th><th>Category</th><th>Unit</th><th>Vendor</th><th>Rate</th></tr></thead><tbody>${rows.map(p=>`<tr><td>${esc(p.name||'Blank source row')}</td><td>${esc(p.category||'—')}</td><td>${esc(p.unit||'—')}</td><td>${esc(p.vendor_name||'—')}</td><td class="money">${money(p.rate)}</td></tr>`).join('')}</tbody></table></div>`;return `<div class="table-wrap"><table><thead><tr><th>Vendor</th><th>TIN</th><th>Mobile</th><th>Address</th><th>Budget</th></tr></thead><tbody>${rows.map(v=>`<tr><td>${esc(v.vendor_name)}</td><td>${esc(v.tin_number||'—')}</td><td>${esc(v.contact_number||'—')}</td><td>${esc(v.address||'—')}</td><td class="money">${money(v.total_budget)}</td></tr>`).join('')}</tbody></table></div>`}
function rates(cards=false){if(cards){const latest=new Map();state.rates.forEach(r=>{if(!latest.has(r.product_id))latest.set(r.product_id,r)});const rows=[...latest.values()];return `<div class="toolbar"><input id="cardSearch" class="search" placeholder="Search price cards…"></div><div id="cardResults" class="grid price-cards">${priceCardHtml(rows)}</div>`}return `<div class="toolbar"><input id="rateSearch" class="search" placeholder="Search rates…"></div><div id="rateResults">${rateTable(state.rates)}</div>`}
function rateTable(rows){return rows.length?`<div class="table-wrap"><table><thead><tr><th>Date</th><th>Product</th><th>Vendor</th><th>Unit</th><th>Rate</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.effective_date)}</td><td>${esc(r.product_name)}</td><td>${esc(r.vendor_name||'—')}</td><td>${esc(r.unit||'—')}</td><td class="money">${money(r.rate)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty"><strong>No rate history yet</strong>Rates are saved automatically from bills.</div>'}
function priceCardHtml(rows){return rows.length?rows.map(r=>`<article class="card price-card"><h3>${esc(r.product_name)}</h3><div class="rate">${money(r.rate)} <small>/ ${esc(r.unit||'unit')}</small></div><p class="muted">${esc(r.vendor_name||'No vendor')} · ${esc(r.effective_date)}</p></article>`).join(''):'<div class="empty"><strong>No price cards yet</strong>Save a bill to create price cards.</div>'}
function inventory(){const map=new Map(state.inventory.map(i=>[i.product_id,i]));return `<div class="toolbar"><input id="inventorySearch" class="search" placeholder="Search inventory…"></div><div id="inventoryResults"><div class="table-wrap"><table><thead><tr><th>Product</th><th>Unit</th><th>On hand</th><th>Reorder level</th><th>Status</th></tr></thead><tbody>${state.products.filter(p=>p.name).map(p=>{const x=map.get(p.id)||{};const low=Number(x.quantity||0)<=Number(x.reorder_level||0);return `<tr><td>${esc(p.name)}</td><td>${esc(p.unit||'—')}</td><td>${Number(x.quantity||0)}</td><td>${Number(x.reorder_level||0)}</td><td><span class="badge ${low?'warn':'good'}">${low?'Low':'In stock'}</span></td></tr>`}).join('')}</tbody></table></div></div>`}
function reports(){const agg={};state.bills.forEach(b=>agg[b.vendor_name]=(agg[b.vendor_name]||0)+Number(b.total_amount));const rows=Object.entries(agg).sort((a,b)=>b[1]-a[1]),max=rows[0]?.[1]||1;return `<div class="grid content-grid"><section class="card"><div class="section-head"><h3>Spend by vendor</h3></div><div class="report-bars">${rows.length?rows.slice(0,10).map(([n,v])=>`<div class="bar-row"><span>${esc(n)}</span><div class="bar"><i style="width:${v/max*100}%"></i></div><strong>${money(v)}</strong></div>`).join(''):'<div class="empty">No report data yet.</div>'}</div></section><section class="card"><h3>Report summary</h3><div class="setting-row"><span>Total bills</span><strong>${state.bills.length}</strong></div><div class="setting-row"><span>Total spend</span><strong>${money(state.bills.reduce((a,b)=>a+Number(b.total_amount),0))}</strong></div><div class="setting-row"><span>Vendors used</span><strong>${rows.length}</strong></div></section></div>`}
function settings(){return `<section class="card"><h3>Settings</h3><div class="setting-row"><div><strong>Currency</strong><p class="muted">Used throughout the application</p></div><span>MVR</span></div><div class="setting-row"><div><strong>Database</strong><p class="muted">Supabase live connection</p></div><span class="badge good">Connected</span></div><div class="setting-row"><div><strong>Theme</strong><p class="muted">Amber & charcoal</p></div><span>System default</span></div></section>`}
function backup(){return `<section class="card"><h3>Backup and Restore</h3><p class="muted" style="margin:8px 0 20px">Download your master data as JSON. Restore validates the file before replacing data.</p><div class="toolbar" style="justify-content:flex-start"><button id="downloadBackup" class="btn primary">Download backup</button><label class="btn">Restore backup<input id="restoreFile" type="file" accept="application/json" hidden></label></div></section>`}
function render(){const f={dashboard,newBill,'bill-history':()=>`<div class="toolbar"><input id="billSearch" class="search" placeholder="Search bills…"></div><div id="billResults">${billTable(state.bills)}</div>`,products:()=>listPage('products'),vendors:()=>listPage('vendors'),'rate-history':()=>rates(false),'price-cards':()=>rates(true),inventory,reports,settings,backup};$('#page').innerHTML=f[state.page]();bindPage()}
function bindPage(){
 if(state.page==='new-bill')bindBill();
 const searchMap={billSearch:['billResults',q=>billTable(state.bills.filter(b=>`${b.bill_number} ${b.vendor_name}`.toLowerCase().includes(q)))],rateSearch:['rateResults',q=>rateTable(state.rates.filter(r=>`${r.product_name} ${r.vendor_name}`.toLowerCase().includes(q)))],cardSearch:['cardResults',q=>priceCardHtml(state.rates.filter(r=>`${r.product_name} ${r.vendor_name}`.toLowerCase().includes(q)))]};
 Object.entries(searchMap).forEach(([id,[out,fn]])=>{const e=$('#'+id);if(e)e.oninput=()=>$('#'+out).innerHTML=fn(e.value.toLowerCase())});
 if($('#listSearch'))$('#listSearch').oninput=e=>{const q=e.target.value.toLowerCase(),kind=state.page;$('#listResults').innerHTML=dataTable(kind,(kind==='products'?state.products:state.vendors).filter(x=>JSON.stringify(x).toLowerCase().includes(q)))};
 if($('#createRecord'))$('#createRecord').onclick=()=>state.page==='vendors'?openVendor():toast('Products are imported from the master catalogue');
 if($('#downloadBackup'))$('#downloadBackup').onclick=downloadBackup;
 if($('#restoreFile'))$('#restoreFile').onchange=()=>toast('Restore validation is ready; database replacement requires administrator approval.');
}
function openVendor(prefill=''){const d=$('#vendorDialog');d.querySelector('[name=vendor_name]').value=prefill;d.showModal()}
function bindBill(){
 renderItems();$('#vendorSelect').onchange=e=>{if(e.target.value==='__create'){openVendor();e.target.value='';return}state.selectedVendor=state.vendors.find(v=>String(v.id)===e.target.value)||null;const s=$('#vendorSummary');if(!state.selectedVendor){s.classList.add('hidden');return}s.classList.remove('hidden');s.innerHTML=`<div><small>Vendor</small><strong>${esc(state.selectedVendor.vendor_name)}</strong></div><div><small>TIN</small><strong>${esc(state.selectedVendor.tin_number||'Not available')}</strong></div><div><small>Mobile</small><strong>${esc(state.selectedVendor.contact_number||'Not available')}</strong></div>`};
 $('#productSelect').onchange=e=>{const p=state.products.find(x=>String(x.id)===e.target.value);if(p){$('#itemRate').value=p.rate??'';$('#itemUnit').value=p.unit??''}};
 $('#addItem').onclick=()=>{const p=state.products.find(x=>String(x.id)===$('#productSelect').value),quantity=Number($('#itemQty').value),rate=Number($('#itemRate').value);if(!p||quantity<=0||rate<0)return toast('Choose a product, quantity and rate');state.items.push({product_id:p.id,product_name:p.name,quantity,rate,unit:$('#itemUnit').value});renderItems()};
 $('#billForm').onsubmit=saveBill;
}
async function saveBill(e){e.preventDefault();if(!state.selectedVendor)return toast('Select a vendor');if(!state.items.length)return toast('Add at least one product');const fd=new FormData(e.target),total=state.items.reduce((a,x)=>a+x.quantity*x.rate,0);const bill={bill_number:fd.get('bill_number'),bill_date:fd.get('bill_date'),vendor_id:state.selectedVendor.id,vendor_name:state.selectedVendor.vendor_name,vendor_tin:state.selectedVendor.tin_number,vendor_mobile:state.selectedVendor.contact_number,subtotal:total,total_amount:total,payment_status:fd.get('payment_status'),payment_method:fd.get('payment_method'),notes:fd.get('notes')};const {data,error}=await db.from('supply_bills').insert(bill).select().single();if(error)return toast(error.message);const items=state.items.map(x=>({...x,bill_id:data.id}));const rates=state.items.map(x=>({product_id:x.product_id,vendor_id:state.selectedVendor.id,product_name:x.product_name,vendor_name:state.selectedVendor.vendor_name,unit:x.unit,rate:x.rate,bill_id:data.id,effective_date:bill.bill_date}));const [{error:ie},{error:re}]=await Promise.all([db.from('supply_bill_items').insert(items),db.from('supply_rate_history').insert(rates)]);if(ie||re)return toast((ie||re).message);state.items=[];await load();toast('Bill saved');go('bill-history')}
async function saveVendor(e){e.preventDefault();const fd=new FormData(e.target),payload=Object.fromEntries(fd.entries());payload.source_id=Math.max(0,...state.vendors.map(v=>v.source_id||0))+1;payload.total_budget=0;const {data,error}=await db.from('supply_vendors').insert(payload).select().single();if(error)return toast(error.message);state.vendors.push(data);state.vendors.sort((a,b)=>a.vendor_name.localeCompare(b.vendor_name));state.selectedVendor=data;$('#vendorDialog').close();toast('Vendor created');if(state.page==='new-bill'){render();setTimeout(()=>{$('#vendorSelect').value=String(data.id);$('#vendorSelect').dispatchEvent(new Event('change'))})}else render()}
function downloadBackup(){const blob=new Blob([JSON.stringify({version:1,exported_at:new Date().toISOString(),products:state.products,vendors:state.vendors,bills:state.bills,rates:state.rates,inventory:state.inventory},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`supply-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
async function init(){nav();$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';const {error}=await db.auth.signInWithPassword({email:$('#loginEmail').value,password:$('#loginPassword').value});if(error)$('#loginError').textContent=error.message};$('#logoutBtn').onclick=()=>db.auth.signOut();$('#quickBill').onclick=()=>go('new-bill');$('#menuBtn').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');document.querySelectorAll('.close-dialog').forEach(x=>x.onclick=()=>$('#vendorDialog').close());$('#vendorForm').onsubmit=saveVendor;db.auth.onAuthStateChange(async(_,session)=>{if(session){$('#loginView').classList.add('hidden');$('#appShell').classList.remove('hidden');try{await load();render()}catch(e){toast(e.message)}}else{$('#appShell').classList.add('hidden');$('#loginView').classList.remove('hidden')}})}
init();
